name: dmidecode-rs_ci

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: OS version
      run: uname -a
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --  --exact --nocapture
