name: dmidecode-rs_ci

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - if: matrix.os != 'macos-latest'
      name: Run Linux and Windows tests
      run: cargo test --verbose
    - if: matrix.os == 'macos-latest'
      name: Run MacOS tests
      run: cargo test --verbose --skip test_oem_string_valid
